#jangan ganti author nya"
#script tidak 100%work!"
#no wa +6283192644730"
sleep 5
echo -e "\e[92m<<<<<<<<<<<<hecked by M3R4Z>>>>>>>>>>>>\e[0m";
sleep 3
echo -e "\e[93m..................litevirus..................\e[0m";
sleep 2
echo -e "\e[37mauthor=MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mno wa =+6283192644730\e[0m";
sleep 4
echo -e "\e[91mtim =TCT=Termux•Cyber•Tim\e[0m";
sleep 2
echo -e "\e[35myoutube = MR M3R4Z\e[0m";
sleep 5
echo -e "\e[34mauthor tidak bertanggung jawab jika sc di salahgunakan\e[0m";
sleep 4
echo -e "\e[95mlitevirus\e[0m";
sleep 2
echo -e "\e[92mmasukan no target\e[0m";
sleep 2
read -p '}>>>' userinput1;
#
sleep 3
echo -e "\e[33mtunggu sebentar!\e[0m";
sleep 6
echo -e "\e[95mloading......\e[0m";
sleep 9
echo -e "\e[94mloading......\e[0m";
sleep 5
echo -e "\e[37mloading......\e[0m";
sleep 7
echo -e "\e[34mloading......\e[0m";
sleep 3
echo -e "\e[92mloading......\e[0m";
sleep 6
echo -e "\e[31mloading......\e[0m";
sleep 4
echo -e "\e[92mloading......\e[0m";
sleep 3
echo -e "\e[91mmasukan kembali nomor target.\e[0m";
sleep 2
read -p '}>>>' userinput2;
#
sleep 2
echo -e "\e[94mtunggu sebentar\e[0m";
sleep 3
echo -e "\e[94mmemperoses...........\e[0m";
sleep 1
echo -e "\e[32mmemperoses.....\e[0m";
sleep 1
echo -e "\e[91mmemperoses...........\e[0m";
sleep 3
echo -e "\e[93muntuk berhentik tekan CTRL ketik Z\e[0m";
sleep 5
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 1
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[33mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[34mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[91mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[95mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[31mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 3
echo -e "\e[92mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[94mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[35mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 2
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[90mBERHASIL MENGIRIM VIRUS-SUBSCRIBE CHENNEL MR M3R4Z\e[0m";
sleep 4
echo -e "\e[90mjika script tidak perpungsi berarti script sudah tidak work!\e[0m";
sleep 2
echo -e "\e[94msubscribe chennel MR M3R4Z\e[0m";
sleep 5
echo -e "\e[94mketik exit untuk keluar!\e[0m";
sleep 1
read -p '}>>>' userinput4;
#
sleep 3
echo -e "\e[95msubscribe chennel MR M3R4Z\e[0m";
sleep 1
